(function() {var implementors = {};
implementors["trillium_cookies"] = [{"text":"impl <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_cookies/struct.CookiesHandler.html\" title=\"struct trillium_cookies::CookiesHandler\">CookiesHandler</a>","synthetic":false,"types":["trillium_cookies::cookies_handler::CookiesHandler"]}];
implementors["trillium_handlebars"] = [{"text":"impl <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_handlebars/struct.HandlebarsHandler.html\" title=\"struct trillium_handlebars::HandlebarsHandler\">HandlebarsHandler</a>","synthetic":false,"types":["trillium_handlebars::handlebars_handler::HandlebarsHandler"]}];
implementors["trillium_html_rewriter"] = [{"text":"impl <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_html_rewriter/struct.HtmlRewriter.html\" title=\"struct trillium_html_rewriter::HtmlRewriter\">HtmlRewriter</a>","synthetic":false,"types":["trillium_html_rewriter::HtmlRewriter"]}];
implementors["trillium_logger"] = [{"text":"impl <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_logger/struct.Logger.html\" title=\"struct trillium_logger::Logger\">Logger</a>","synthetic":false,"types":["trillium_logger::Logger"]}];
implementors["trillium_proxy"] = [{"text":"impl&lt;C:&nbsp;<a class=\"trait\" href=\"trillium_proxy/trait.Connector.html\" title=\"trait trillium_proxy::Connector\">Connector</a>&gt; <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_proxy/struct.Proxy.html\" title=\"struct trillium_proxy::Proxy\">Proxy</a>&lt;C&gt;","synthetic":false,"types":["trillium_proxy::Proxy"]}];
implementors["trillium_router"] = [{"text":"impl <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_router/struct.Router.html\" title=\"struct trillium_router::Router\">Router</a>","synthetic":false,"types":["trillium_router::router::Router"]}];
implementors["trillium_sessions"] = [{"text":"impl&lt;Store:&nbsp;SessionStore&gt; <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_sessions/struct.SessionHandler.html\" title=\"struct trillium_sessions::SessionHandler\">SessionHandler</a>&lt;Store&gt;","synthetic":false,"types":["trillium_sessions::session_handler::SessionHandler"]}];
implementors["trillium_static"] = [{"text":"impl <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_static/struct.StaticFileHandler.html\" title=\"struct trillium_static::StaticFileHandler\">StaticFileHandler</a>","synthetic":false,"types":["trillium_static::StaticFileHandler"]}];
implementors["trillium_static_compiled"] = [{"text":"impl <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_static_compiled/struct.StaticCompiledHandler.html\" title=\"struct trillium_static_compiled::StaticCompiledHandler\">StaticCompiledHandler</a>","synthetic":false,"types":["trillium_static_compiled::StaticCompiledHandler"]}];
implementors["trillium_tera"] = [{"text":"impl <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_tera/struct.TeraHandler.html\" title=\"struct trillium_tera::TeraHandler\">TeraHandler</a>","synthetic":false,"types":["trillium_tera::tera_handler::TeraHandler"]}];
implementors["trillium_websockets"] = [{"text":"impl&lt;H, Fut&gt; <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_websockets/struct.WebSocket.html\" title=\"struct trillium_websockets::WebSocket\">WebSocket</a>&lt;H&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;H: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/function/trait.Fn.html\" title=\"trait core::ops::function::Fn\">Fn</a>(<a class=\"struct\" href=\"trillium_websockets/struct.WebSocketConn.html\" title=\"struct trillium_websockets::WebSocketConn\">WebSocketConn</a>) -&gt; Fut + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> + 'static,<br>&nbsp;&nbsp;&nbsp;&nbsp;Fut: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/future/future/trait.Future.html\" title=\"trait core::future::future::Future\">Future</a>&lt;Output = <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.unit.html\">()</a>&gt; + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> + 'static,&nbsp;</span>","synthetic":false,"types":["trillium_websockets::WebSocket"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()