(function() {var implementors = {};
implementors["trillium_async_std"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_async_std/struct.ClientConfig.html\" title=\"struct trillium_async_std::ClientConfig\">ClientConfig</a>","synthetic":false,"types":["trillium_async_std::client::ClientConfig"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_async_std/struct.TcpConnector.html\" title=\"struct trillium_async_std::TcpConnector\">TcpConnector</a>","synthetic":false,"types":["trillium_async_std::client::TcpConnector"]}];
implementors["trillium_cookies"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_cookies/struct.CookiesHandler.html\" title=\"struct trillium_cookies::CookiesHandler\">CookiesHandler</a>","synthetic":false,"types":["trillium_cookies::cookies_handler::CookiesHandler"]}];
implementors["trillium_http"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"trillium_http/enum.ReceivedBodyState.html\" title=\"enum trillium_http::ReceivedBodyState\">ReceivedBodyState</a>","synthetic":false,"types":["trillium_http::received_body::ReceivedBodyState"]}];
implementors["trillium_logger"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_logger/struct.Logger.html\" title=\"struct trillium_logger::Logger\">Logger</a>","synthetic":false,"types":["trillium_logger::Logger"]}];
implementors["trillium_native_tls"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_native_tls/struct.NativeTlsConnector.html\" title=\"struct trillium_native_tls::NativeTlsConnector\">NativeTlsConnector</a>&lt;T&gt;","synthetic":false,"types":["trillium_native_tls::client::NativeTlsConnector"]}];
implementors["trillium_rustls"] = [{"text":"impl&lt;C:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_rustls/struct.RustlsConnector.html\" title=\"struct trillium_rustls::RustlsConnector\">RustlsConnector</a>&lt;C&gt;","synthetic":false,"types":["trillium_rustls::client::RustlsConnector"]}];
implementors["trillium_smol"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_smol/struct.ClientConfig.html\" title=\"struct trillium_smol::ClientConfig\">ClientConfig</a>","synthetic":false,"types":["trillium_smol::client::ClientConfig"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_smol/struct.TcpConnector.html\" title=\"struct trillium_smol::TcpConnector\">TcpConnector</a>","synthetic":false,"types":["trillium_smol::client::TcpConnector"]}];
implementors["trillium_static_compiled"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_static_compiled/struct.StaticCompiledHandler.html\" title=\"struct trillium_static_compiled::StaticCompiledHandler\">StaticCompiledHandler</a>","synthetic":false,"types":["trillium_static_compiled::StaticCompiledHandler"]}];
implementors["trillium_tokio"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_tokio/struct.ClientConfig.html\" title=\"struct trillium_tokio::ClientConfig\">ClientConfig</a>","synthetic":false,"types":["trillium_tokio::client::ClientConfig"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"trillium_tokio/struct.TcpConnector.html\" title=\"struct trillium_tokio::TcpConnector\">TcpConnector</a>","synthetic":false,"types":["trillium_tokio::client::TcpConnector"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()